### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by scy5335** [Benjamin-Walker/log-neural-cdes#60]
Hi Ben,
           I run the code with "python run_experiment.py --pytorch_experiment" and I meet the following bug.
![afa0e704f6f4bf05acfce238cb085990](https://github.com/user-attachments/assets/ee07bc44-41f5-4c07-b9b0-c771ef523162)
           I output the "labels.to(torch.int64)" and "num_classes" and find that there is not "1" in "labels.to(torch.int64)" so that the function "unique" will make "num_classes" to be "4". How can I fix this bug?

**Comment by Benjamin-Walker** [comment]
Hi Su Chengye,

Thank you for bringing this to my attention! 

I’ve just merged a pull request that moves the calculation of num_classes to ensure it captures the complete set of unique classes in labels before any data splitting. Previously, this calculation happened after splitting, which could lead to incorrect class counts if certain classes weren’t present in all subsets. 

Please let me know if this fixes your issue!

Kind regards,

Ben

**Comment by scy5335** [comment]
Dear Ben,

Thanks for your reply. The bug is fixed now.

Best wishes,

Su Chengye
